### ISSUE TITLE
_roi_pooling.so: undefined symbol: _Py_Dealloc

### ISSUE THREAD

**Issue by samet-akcay** [ruotianluo/pytorch-faster-rcnn#1]
Hi,
I very much appreciate you made this repository publicly available to use. Before getting my hands dirtier, I tried to run `./tools/demo.py`; however, got the following error:
```
GPU_ID=0
CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py
Traceback (most recent call last):
  File "./tools/demo.py", line 29, in <module>
    from nets.vgg16 import vgg16
  File "/home/sam/projects/faster.rcnn.pytorch/tools/../lib/nets/vgg16.py", line 10, in <module>
    from nets.network import Network
  File "/home/sam/projects/faster.rcnn.pytorch/tools/../lib/nets/network.py", line 28, in <module>
    from layer_utils.roi_pooling.roi_pool import RoIPoolFunction
  File "/home/sam/projects/faster.rcnn.pytorch/tools/../lib/layer_utils/roi_pooling/roi_pool.py", line 3, in <module>
    from _ext import roi_pooling
  File "/home/sam/projects/faster.rcnn.pytorch/tools/../lib/layer_utils/roi_pooling/_ext/roi_pooling/__init__.py", line 3, in <module>
    from ._roi_pooling import lib as _lib, ffi as _ffi
ImportError: /home/sam/projects/faster.rcnn.pytorch/tools/../lib/layer_utils/roi_pooling/_ext/roi_pooling/_roi_pooling.so: undefined symbol: _Py_Dealloc
```
Any ideas what could cause the problem?

**Comment by ruotianluo** [comment]
I've never met this problem. I copied the roi pooling module from other repository, and it works fine for me.

However, you can download the model trained by crop and resize, and comment out all the Roi pooling related code. It could still work.

(I fixed some bugs, so if you want to do so, please pull from master again)

**Comment by akczay** [comment]
Thanks, will try

**Comment by brisker** [comment]
@ruotianluo 
it seems that the roi_pooling layer only support batch_size==1.
So does this total project does not support batch_size>1?
