### ISSUE TITLE
When I run demo, it says No module named crop_and_resize. I thought it is from lib/layer_utils/roi_align/_ext/crop_and_resize/

### ISSUE THREAD

**Issue by chang0977** [ruotianluo/pytorch-faster-rcnn#102]

**Comment by chang0977** [comment]
{GPU_ID} ./tools/demo.py
Traceback (most recent call last):
  File "./tools/demo.py", line 29, in <module>
    from nets.vgg16 import vgg16
  File "/home/hyunbae/pytorch-faster-rcnn/tools/../lib/nets/vgg16.py", line 10, in <module>
    from nets.network import Network
  File "/home/hyunbae/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 28, in <module>
    from layer_utils.roi_align.crop_and_resize import CropAndResizeFunction
  File "/home/hyunbae/pytorch-faster-rcnn/tools/../lib/layer_utils/roi_align/crop_and_resize.py", line 7, in <module>
    from ._ext import crop_and_resize as _backend
  File "/home/hyunbae/pytorch-faster-rcnn/tools/../lib/layer_utils/roi_align/_ext/crop_and_resize/__init__.py", line 3, in <module>
    from ._crop_and_resize import lib as _lib, ffi as _ffi
ImportError: No module named _crop_and_resize

**Comment by ruotianluo** [comment]
Did you creatly compile the roi_align?

**Comment by chang0977** [comment]
thanks I solved it with recompliing those. However, I found another error
IOError: [Errno 2] No such file or directory: 'output/res101/voc_2007_trainval+voc_2012_trainval/default/res101_faster_rcnn_iter_110000.pth'

I linked 'default', under the 'output' folder, file to the pretrained model from Google drive and another file under 'data' folder to VOC2007devkit that I downloaded. I think I put the files in the right places but still meeting some errors I hope to know how to solve this.
