### ISSUE TITLE
key error when train by myself with "./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc res101"

### ISSUE THREAD

**Issue by BrightXiaoHan** [ruotianluo/pytorch-faster-rcnn#104]
When I train the model by myself, it raise a KeyError when load res101 parameters from pre-trained model. How can I solve this.

Loading initial model weights from data/imagenet_weights/res101.pth
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/home/hanbing/ExtraDisk/GithubProject/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 348, in train_net
    sw.train_model(max_iters)
  File "/home/hanbing/ExtraDisk/GithubProject/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 224, in train_model
    lr, last_snapshot_iter, stepsizes, np_paths, ss_paths = self.initialize()
  File "/home/hanbing/ExtraDisk/GithubProject/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 167, in initialize
    self.net.load_pretrained_cnn(torch.load(self.pretrained_model))
  File "/home/hanbing/ExtraDisk/GithubProject/pytorch-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 177, in load_pretrained_cnn
    self.resnet.load_state_dict({k: state_dict[k] for k in list(self.resnet.state_dict())})
  File "/home/hanbing/ExtraDisk/GithubProject/pytorch-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 177, in <dictcomp>
    self.resnet.load_state_dict({k: state_dict[k] for k in list(self.resnet.state_dict())})
KeyError: 'bn1.num_batches_tracked'
Command exited with non-zero status 1
3.40user 0.37system 0:03.78elapsed 99%CPU (0avgtext+0avgdata 577576maxresident)k
0inputs+16outputs (0major+146467minor)pagefaults 0swaps

**Comment by ruotianluo** [comment]
It's fixed in master.
https://github.com/goodlux/pytorch/commit/6f935acf96c36c1d2b43ae7822a549baaf953a59

**Comment by BrightXiaoHan** [comment]
But I have already got the master branch code.

**Comment by rnjtsh** [comment]
Same for me. I cloned using the link, but still getting the same error. If you could get the issue resolved please help.

**Comment by ruotianluo** [comment]
It’s fixed in PyTorch master

**Comment by ruotianluo** [comment]
It looks like a commit fixing this problem, i haven’t personally tried.

**Comment by SkylerZheng** [comment]
I also have this problem when I tried to use demo.py. It's weird. It used to work fine.

**Comment by SkylerZheng** [comment]
I got it fixed. I think it's because the pytorch version. This repo works well with torch version of 0.4.0, not 0.4.1

**Comment by redhat12345** [comment]
I have installed torch==0.4.0 and it solved

**Comment by ruotianluo** [comment]
Fixed in #126
