### ISSUE TITLE
Getting rpn_loss_box of NaN when using custom dataset

### ISSUE THREAD

**Issue by crawphish** [ruotianluo/pytorch-faster-rcnn#105]
Hi,

I am using a custom dataset and get about 120 iterations in before the rpn_loss_box reports as NaN.

```
iter: 80 / 10000, total loss: 0.941651
 >>> rpn_loss_cls: 0.063259
 >>> rpn_loss_box: 0.815982
 >>> loss_cls: 0.047017
 >>> loss_box: 0.015394
 >>> lr: 0.001000
speed: 0.271s / iter
iter: 100 / 10000, total loss: 1.232251
 >>> rpn_loss_cls: 0.071523
 >>> rpn_loss_box: 1.027229
 >>> loss_cls: 0.096656
 >>> loss_box: 0.036843
 >>> lr: 0.001000
speed: 0.270s / iter
Wrote snapshot to: /home/hd006351/Documents/pytorch-faster-rcnn/output/vgg16/2018_train/default/vgg16_faster_rcnn_iter_101.pth
iter: 120 / 10000, total loss: 2.593077
 >>> rpn_loss_cls: 1.008498
 >>> rpn_loss_box: 1.346431
 >>> loss_cls: 0.186908
 >>> loss_box: 0.051240
 >>> lr: 0.000100
speed: 0.270s / iter
iter: 140 / 10000, total loss: nan
 >>> rpn_loss_cls: 0.682706
 >>> rpn_loss_box: nan
 >>> loss_cls: 0.000110
 >>> loss_box: 0.000000
 >>> lr: 0.000100
speed: 0.270s / iter
```

I have read about exploding gradients and thought it might have something to do with that, but am not really sure where to start fixing it. Do you have any advice on what I might be able to do to fix it?

Thanks

**Comment by crawphish** [comment]
I'll test it with ResNet and see if that helps. If I were to add the gradient clipping where would I do that?

**Comment by ruotianluo** [comment]
Say clip the gradient to norm 10. I haven't tried personally but I've known other people doing this.

**Comment by crawphish** [comment]
I had no luck with using ResNet, it yielded the same result.

I noticed in another thread about checking bounding box values, and noticed that mine were already index 0-based. This meant that the -1 from:

```
x1 = float(bbox.find('xmin').text) - 1
y1 = float(bbox.find('ymin').text) - 1
x2 = float(bbox.find('xmax').text) - 1
y2 = float(bbox.find('ymax').text) - 1
```

was making the bounding box values negative. I have removed the '-1' from those lines. I am now encountering a new error:

```
wrote gt roidb to /home/me/Documents/pytorch-faster-rcnn/data/cache/2018_train_gt_roidb.pkl
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/trainval_net.py", line 75, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 75, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 72, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/me/Documents/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 303, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/me/Documents/pytorch-faster-rcnn/tools/../lib/datasets/imdb.py", line 118, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError
Command exited with non-zero status 1
```
I haven't had a chance to look into it yet, I'll continue trying to fix it tomorrow. Is this like anything you've seen before?

**Comment by ruotianluo** [comment]
This means your xmax is less than xmin I guess.

**Comment by crawphish** [comment]
To anyone who is also having the same problem and who wants to know how I solved it. This was an issue in that the code is written for annotations that are index 1-based (the first row/column of pixels is index 1, not 0), but I had written my annotations as 0-based.

I wrote a small bit of code to check my annotations for any errors, this will help you find out if yours is 0-based.

```
def validate_boxes():
    folder = "/home/you/path/to/data/Annotations/"

    for file in os.listdir(folder):
        tree = et.parse(folder+file)
        root = tree.getroot()

        for box in root.findall('object/bndbox'):
            xmin = int(box.find('xmin').text)
            xmax = int(box.find('xmax').text)
            ymin = int(box.find('ymin').text)
            ymax = int(box.find('ymax').text)

            if xmin < 0:
                print("Error in "+ file +": xmin less than 0")
            elif xmax < 0:
                print("Error in "+ file +": xmax less than 0")
            elif ymin < 0:
                print("Error in "+ file +": ymin less than 0")
            elif ymax < 0:
                print("Error in "+ file +": ymax less than 0")
            elif xmin > 500:
                print("Error in "+ file +": xmin greater than 500")
            elif xmax > 500:
                print("Error in "+ file +": xmax greater than 500")
            elif ymin > 375:
                print("Error in "+ file +": ymin greater than 375")
            elif ymax > 375:
                print("Error in "+ file +": ymax greater than 375")
            elif xmin > xmax:
                print("Error in "+ file +": xmin greater than xmax")
            elif ymin > ymax:
                print("Error in "+ file +": ymin greater than ymax")
            elif xmin == 0:
                print("Warning in "+ file +": xmin equals zero")
            elif ymin == 0:
                print("Warning in "+ file +": ymin equals zero")
            elif xmax == 0:
                print("Warning in "+ file +": xmax equals zero")
            elif ymax == 0:
                print("Warning in "+ file +": ymax equals zero")
```
If you find that your annotations being 0-based is the problem, you can either go through and add one to each of the values or modify the code in the following places:

In your datasets imdb file, assuming you based it on the pascal_voc file, remove the -1 from where the values are read. It should look like this:

           ```
 x1 = float(bbox.find('xmin').text)
            y1 = float(bbox.find('ymin').text)
            x2 = float(bbox.find('xmax').text)
            y2 = float(bbox.find('ymax').text)
```

Next you need to go to imdb.py lines 116 and 117 and change them to this:


```
boxes[:, 0] = widths[i] - oldx2# - 1
boxes[:, 2] = widths[i] - oldx1# - 1
```

I always see people coming into threads a year later asking how the issue was finally solved, so hopefully this helps someone :)
