### ISSUE TITLE
Why set eval mode durint training?

### ISSUE THREAD

**Issue by zhoulukuan** [ruotianluo/pytorch-faster-rcnn#113]
Hi, I'm learning your code. And I found such codes in lib/nets/resnet_v1.py:
```python
  def train(self, mode=True):
    # Override train so that the training mode is set as we want
    nn.Module.train(self, mode)
    if mode:
      # Set fixed blocks to be in eval mode (not really doing anything)
      self.resnet.eval()
      if cfg.RESNET.FIXED_BLOCKS <= 3:
        self.resnet.layer4.train()
      if cfg.RESNET.FIXED_BLOCKS <= 2:
        self.resnet.layer3.train()
      if cfg.RESNET.FIXED_BLOCKS <= 1:
        self.resnet.layer2.train()
      if cfg.RESNET.FIXED_BLOCKS == 0:
        self.resnet.layer1.train()

      # Set batchnorm always in eval mode during training
      def set_bn_eval(m):
        classname = m.__class__.__name__
        if classname.find('BatchNorm') != -1:
          m.eval()

      self.resnet.apply(set_bn_eval)
```
I feel confused why set eval mode during training, perhaps we hope to keep BatchNorm unchanged? But why? @ruotianluo What's function of those codes?

**Comment by ruotianluo** [comment]
Because batch norm usually requires fairly large batch size, however in this repo, batch size is one.  You cannot learn batch norm with batch size 1

**Comment by zhoulukuan** [comment]
@ruotianluo Thank you very much. I get this point. I have trained res101 on COCO with your scripts(using tf pretrained model). However, I got 32 mAP. It seems a little worse than number you give(35.4). 
Is it a problem with my training? Or do I need to change the default parameters (such as the maximum number of iterations, learning rate) to reproduce your result?

**Comment by zhoulukuan** [comment]
@ruotianluo Besides, I checked the original paper of ResNet and found the result on COCO 2015 competition was about 27.2(without any tricks). So I feel confused about what result should I get using the default parameters without any change. Could you give me some advice?

**Comment by TP0609** [comment]
> @ruotianluo Thank you very much. I get this point. I have trained res101 on COCO with your scripts(using tf pretrained model). However, I got 32 mAP. It seems a little worse than number you give(35.4).
> Is it a problem with my training? Or do I need to change the default parameters (such as the maximum number of iterations, learning rate) to reproduce your result?

hello !　　　I have some questions on trained res101 on COCO:

Loading model check point from output/res101/coco_2014_train+coco_2014_valminusminival/default/res101_faster_rcnn_iter_70000.pth
Traceback (most recent call last):
  File "./tools/test_net.py", line 116, in <module>
    net.load_state_dict(torch.load(args.model, map_location=lambda storage, loc: storage))
  File "/home/tp/pytorch-faster-rcnn-0.4/tools/../lib/nets/network.py", line 561, in load_state_dict
    for k, v in state_dict.items() if k in self.state_dict()}  #torch0.4-1.1
  File "/home/tp/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for resnetv1:
        size mismatch for rpn_cls_score_net.bias: copying a param of torch.Size([24]) from checkpoint, where the shape is torch.Size([18]) in current model.
        size mismatch for rpn_cls_score_net.weight: copying a param of torch.Size([24, 512, 1, 1]) from checkpoint, where the shape is torch.Size([18, 512, 1, 1]) in current model.
        size mismatch for rpn_bbox_pred_net.bias: copying a param of torch.Size([48]) from checkpoint, where the shape is torch.Size([36]) in current model.
        size mismatch for rpn_bbox_pred_net.weight: copying a param of torch.Size([48, 512, 1, 1]) from checkpoint, where the shape is torch.Size([36, 512, 1, 1]) in current model.
        size mismatch for cls_score_net.bias: copying a param of torch.Size([81]) from checkpoint, where the shape is torch.Size([21]) in current model.
        size mismatch for cls_score_net.weight: copying a param of torch.Size([81, 2048]) from checkpoint, where the shape is torch.Size([21, 2048]) in current model.
        size mismatch for bbox_pred_net.bias: copying a param of torch.Size([324]) from checkpoint, where the shape is torch.Size([84]) in current model.
        size mismatch for bbox_pred_net.weight: copying a param of torch.Size([324, 2048]) from checkpoint, where the shape is torch.Size([84, 2048]) in current model.
Command exited with non-zero status 1
4.52user 1.27system 0:04.89elapsed 118%CPU (0avgtext+0avgdata 2882496maxresident)k
414560inputs+32outputs (0major+685440minor)pagefaults 0swaps


can you help me?

**Comment by Dawn-LX** [comment]
> > @ruotianluo Thank you very much. I get this point. I have trained res101 on COCO with your scripts(using tf pretrained model). However, I got 32 mAP. It seems a little worse than number you give(35.4).
> > Is it a problem with my training? Or do I need to change the default parameters (such as the maximum number of iterations, learning rate) to reproduce your result?
> 
> hello !　　　I have some questions on trained res101 on COCO:
> 
> Loading model check point from output/res101/coco_2014_train+coco_2014_valminusminival/default/res101_faster_rcnn_iter_70000.pth
> Traceback (most recent call last):
> File "./tools/test_net.py", line 116, in
> net.load_state_dict(torch.load(args.model, map_location=lambda storage, loc: storage))
> File "/home/tp/pytorch-faster-rcnn-0.4/tools/../lib/nets/network.py", line 561, in load_state_dict
> for k, v in state_dict.items() if k in self.state_dict()} #torch0.4-1.1
> File "/home/tp/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for resnetv1:
> size mismatch for rpn_cls_score_net.bias: copying a param of torch.Size([24]) from checkpoint, where the shape is torch.Size([18]) in current model.
> size mismatch for rpn_cls_score_net.weight: copying a param of torch.Size([24, 512, 1, 1]) from checkpoint, where the shape is torch.Size([18, 512, 1, 1]) in current model.
> size mismatch for rpn_bbox_pred_net.bias: copying a param of torch.Size([48]) from checkpoint, where the shape is torch.Size([36]) in current model.
> size mismatch for rpn_bbox_pred_net.weight: copying a param of torch.Size([48, 512, 1, 1]) from checkpoint, where the shape is torch.Size([36, 512, 1, 1]) in current model.
> size mismatch for cls_score_net.bias: copying a param of torch.Size([81]) from checkpoint, where the shape is torch.Size([21]) in current model.
> size mismatch for cls_score_net.weight: copying a param of torch.Size([81, 2048]) from checkpoint, where the shape is torch.Size([21, 2048]) in current model.
> size mismatch for bbox_pred_net.bias: copying a param of torch.Size([324]) from checkpoint, where the shape is torch.Size([84]) in current model.
> size mismatch for bbox_pred_net.weight: copying a param of torch.Size([324, 2048]) from checkpoint, where the shape is torch.Size([84, 2048]) in current model.
> Command exited with non-zero status 1
> 4.52user 1.27system 0:04.89elapsed 118%CPU (0avgtext+0avgdata 2882496maxresident)k
> 414560inputs+32outputs (0major+685440minor)pagefaults 0swaps
> 
> can you help me?

same problem, have you solved it?

**Comment by minji-o-j** [comment]
@Dawn-LX @TP0609 
I changed this part according to the model I used, and it was solved.
`demonet = 'vgg16' # Network to use [vgg16 res101]`
