### ISSUE TITLE
python coco api

### ISSUE THREAD

**Issue by foralliance** [ruotianluo/pytorch-faster-rcnn#115]
@ruotianluo  HI

when i compile coco, run:
```
cd coco/PythonAPI
make
```

display:
```
jmx@jmx-System-Product-Name:~/pytorch-faster-rcnn/data/coco/PythonAPI$ make
python setup.py build_ext --inplace
running build_ext
cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    ext_modules= ext_modules
  File "/home/jmx/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/jmx/.local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    full_module_name=module_name)
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 776, in compile
    return compile_single(source, options, full_module_name)
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 725, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 477, in run_pipeline
    context = options.create_context()
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
    from .Visitor import VisitorTransform
  File "Cython/Compiler/Visitor.py", line 17, in init Cython.Compiler.Visitor
  File "/home/jmx/.local/lib/python2.7/site-packages/Cython/Compiler/ExprNodes.py", line 46, in <module>
    from .Pythran import (to_pythran, is_pythran_supported_type, is_pythran_supported_operation_type,
ImportError: cannot import name pythran_is_numpy_func_supported
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1
```

I think the problem caused by the **numpy version(1.15.3)**, when reduces  **numpy version(1.11.0)**, but it still has an error.

how i solve it??many many thanks

**Comment by NikolasBielski** [comment]
Was this resolved?
