### ISSUE TITLE
run demo err with KeyError: 'resnet.bn1.num_batches_tracked'

### ISSUE THREAD

**Issue by YCY1997** [ruotianluo/pytorch-faster-rcnn#125]
Traceback (most recent call last):
  File "./tools/demo.py", line 164, in <module>
    torch.load(saved_model, map_location=lambda storage, loc: storage))
  File "/home/yue/Downloads/pytorch-faster-rcnn-master/tools/../lib/nets/network.py", line 522, in load_state_dict
    for k in list(self.state_dict())})
  File "/home/yue/Downloads/pytorch-faster-rcnn-master/tools/../lib/nets/network.py", line 522, in <dictcomp>
    for k in list(self.state_dict())})
KeyError: 'resnet.bn1.num_batches_tracked'

just as i run demo.py,its err

**Comment by 28150722** [comment]
I also encountered this problem. Has anyone successfully solved it?

**Comment by lcf000000** [comment]
The provided trained model is old by author, it can't match the new version model format.
You should train a new model in your testing pytorch version.
