### ISSUE TITLE
KeyError: 'resnet.bn1.num_batches_tracked'

### ISSUE THREAD

**Issue by AI-MD** [ruotianluo/pytorch-faster-rcnn#128]
I got an error message below when I executed the demo with the trained model using res101 on VOC dataset : 

Traceback (most recent call last):
  File "./tools/demo.py", line 164, in <module>
    torch.load(saved_model, map_location=lambda storage, loc: storage))
  File "//pytorch-faster-rcnn/tools/../lib/nets/network.py", line 522, in load_state_dict
    for k in list(self.state_dict())})
  File "//pytorch-faster-rcnn/tools/../lib/nets/network.py", line 522, in <dictcomp>
    for k in list(self.state_dict())})
KeyError: 'resnet.bn1.num_batches_tracked'

My PyTorch version is 1.0.
How can I solve this?

**Comment by VikrantKarale** [comment]
Please make the changes as per the [link](https://github.com/ruotianluo/pytorch-faster-rcnn/pull/126/files)

**Comment by zhl95** [comment]
> Please make the changes as per the [link](https://github.com/ruotianluo/pytorch-faster-rcnn/pull/126/files)

network.py load method need to be updated accordingly.
