### ISSUE TITLE
Typeerror when train by myself with "./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc res101"

### ISSUE THREAD

**Issue by fuchuanguang** [ruotianluo/pytorch-faster-rcnn#141]
Solving...
Loading initial model weights from data/imagenet_weights/res101.pth
Loaded.
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 164, in <module>
    max_iters=args.max_iters)
  File "/home/fucg/pytorch/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 393, in train_net
    sw.train_model(max_iters)
  File "/home/fucg/pytorch/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 286, in train_model
    self.net.train_step_with_summary(blobs, self.optimizer)
  File "/home/fucg/pytorch/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 501, in train_step_with_summary
    summary = self._run_summary_op()
  File "/home/fucg/pytorch/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 348, in _run_summary_op
    summaries.append(self._add_gt_image_summary())
  File "/home/fucg/pytorch/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 67, in _add_gt_image_summary
    image[0].astype('float32') / 255.0, dataformats='HWC')
TypeError: image() got an unexpected keyword argument 'dataformats'
Command exited with non-zero status 1
5.52user 4.88system 0:14.29elapsed 72%CPU (0avgtext+0avgdata 1809768maxresident)k
0inputs+1280outputs (0major+409618minor)pagefaults 0swaps

**Comment by jiafw** [comment]
If you use the tensorboardX==1.6,you can solve this problem!
