### ISSUE TITLE
TypeError: indexing a tensor with an object of type torch.cuda.LongTensor.

### ISSUE THREAD

**Issue by barrykui** [ruotianluo/pytorch-faster-rcnn#23]
Dear ruotian, thank you for your great implementation and publication.  However, after I finished the configure, I got the following error:
 
```
----------------type(order.data): <class 'torch.cuda.LongTensor'>
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/home/jsptgpu/barry/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 353, in train_net
    sw.train_model(max_iters)
  File "/home/jsptgpu/barry/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 260, in train_model
    self.net.train_step_with_summary(blobs, self.optimizer)
  File "/home/jsptgpu/barry/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 453, in train_step_with_summary
    self.forward(blobs['data'], blobs['im_info'], blobs['gt_boxes'])
  File "/home/jsptgpu/barry/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 378, in forward
    rois, cls_prob, bbox_pred = self._predict()
  File "/home/jsptgpu/barry/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 350, in _predict
    rois = self._region_proposal(net_conv)
  File "/home/jsptgpu/barry/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 256, in _region_proposal
    rois, roi_scores = self._proposal_layer(rpn_cls_prob, rpn_bbox_pred) # rois, roi_scores are varible
  File "/home/jsptgpu/barry/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 84, in _proposal_layer
    self._feat_stride, self._anchors, self._num_anchors)
  File "/home/jsptgpu/barry/pytorch-faster-rcnn/tools/../lib/layer_utils/proposal_layer.py", line 43, in proposal_layer
    proposals = proposals[order.data, :]
  File "/home/jsptgpu/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 69, in __getitem__
    return Index(key)(self)
  File "/home/jsptgpu/anaconda2/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 16, in forward
    result = i.index(self.index)
TypeError: indexing a tensor with an object of type torch.cuda.LongTensor. The only supported types are integers, slices, numpy scalars and torch.cuda.LongTensor or torch.cuda.ByteTensor as the only argument.
Command exited with non-zero status 1
423.86user 6.79system 7:11.02elapsed 99%CPU (0avgtext+0avgdata 2068360maxresident)k
0inputs+892960outputs (0major+2095481minor)pagefaults 0swaps
```

Any ideas what could cause the problem?

**Comment by ruotianluo** [comment]
This is weird. What's your.version of pytorch.

**Comment by barrykui** [comment]
0.1.12

```
$ python -c "import torch ;print torch.__version__" 
0.1.12
```

**Comment by ruotianluo** [comment]
Use 0.2 for the master branch.

**Comment by barrykui** [comment]
OK, Thank you, I'll try it right now.
