### ISSUE TITLE
undefined symbol: state

### ISSUE THREAD

**Issue by aliceyayunji** [ruotianluo/pytorch-faster-rcnn#26]
When I try to run the demo, I get the following error: 
pattern@pattern-58:~/workspace/jiyy/pytorch-faster-rcnn$ CUDA_VISIBLE_DEVICES=0 ./tools/demo.py
Traceback (most recent call last):
  File "./tools/demo.py", line 22, in <module>
    from model.test import im_detect
  File "/home/pattern/workspace/jiyy/pytorch-faster-rcnn/tools/../lib/model/test.py", line 20, in <module>
    from model.nms_wrapper import nms
  File "/home/pattern/workspace/jiyy/pytorch-faster-rcnn/tools/../lib/model/nms_wrapper.py", line 11, in <module>
    from nms.pth_nms import pth_nms
  File "/home/pattern/workspace/jiyy/pytorch-faster-rcnn/tools/../lib/nms/pth_nms.py", line 2, in <module>
    from ._ext import nms
  File "/home/pattern/workspace/jiyy/pytorch-faster-rcnn/tools/../lib/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /home/pattern/workspace/jiyy/pytorch-faster-rcnn/tools/../lib/nms/_ext/nms/_nms.so: **undefined symbol: state**

**Comment by ruotianluo** [comment]
Never seen this before. What gpu do you have, and do you change -arch option according to you gpu?

**Comment by aliceyayunji** [comment]
Ubuntu 16.04.3
TITAN Xp
Cuda 8.0 installed

**Comment by ruotianluo** [comment]
Try sm_61?

**Comment by aliceyayunji** [comment]
recompiled the nms with sm_61, not work, the same error.

**Comment by aliceyayunji** [comment]
It works fine with  TITAN X (Pascal)

**Comment by ruotianluo** [comment]
I don't have a TITAN Xp, so I can't help here.

**Comment by SONGLOVEWANG** [comment]
I have this problem too.Have you solved it?

**Comment by DebangLi** [comment]
I met the same error with pytorch 0.2.0_post2, then I upgrade the pytorch version to 0.2.0_post3 and 
recompiled it, the problem is solved.
