### ISSUE TITLE
happened to a error when run build.py 

### ISSUE THREAD

**Issue by lianshushu** [ruotianluo/pytorch-faster-rcnn#30]
Anyone can help me about the above question when I run the build.py ? thank you so much.

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DWITH_CUDA -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/include/python2.7 -c _roi_pooling.c -o ./_roi_pooling.o
In file included from /usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _roi_pooling.c:483:
/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:9:18: fatal error: cuda.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 690, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/cffi/recompiler.py", line 1513, in recompile
    compiler_verbose, debug)
  File "/usr/local/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/local/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by ruotianluo** [comment]
Shouldn't you use nvcc to compile?
