### ISSUE TITLE
Run into memory error during training

### ISSUE THREAD

**Issue by chienyiwang** [ruotianluo/pytorch-faster-rcnn#44]
Hi, I am currently training my own dataset using your framework. I was able to train with 110000 iterations (following VOC07+12 protocol), however when I enlarge the number of iteration to 490000, it stopped at  iteration 180000 with the following error message... Do you have any idea what could be the reason? Thank you very much!

`Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/home/cwang/project/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 348, in train_net
    sw.train_model(max_iters)
  File "/home/cwang/project/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 255, in train_model
    self.net.train_step_with_summary(blobs, self.optimizer)
  File "/home/cwang/project/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 478, in train_step_with_summary
    summary = self._run_summary_op()
  File "/home/cwang/project/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 347, in _run_summary_op
    summaries += self._add_act_summary(key, var)
  File "/home/cwang/project/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 66, in _add_act_summary
    return tb.summary.histogram('ACT/' + key + '/activations', tensor.data.cpu().numpy(), bins='auto'),
  File "/home/cwang/anaconda3/envs/tf11_py27/lib/python2.7/site-packages/tensorboardX/summary.py", line 113, in histogram
    hist = make_histogram(values.astype(float), bins)
  File "/home/cwang/anaconda3/envs/tf11_py27/lib/python2.7/site-packages/tensorboardX/summary.py", line 131, in make_histogram
    bucket=counts)
  File "/home/cwang/anaconda3/envs/tf11_py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 508, in init
    copy.extend(field_value)
  File "/home/cwang/anaconda3/envs/tf11_py27/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 275, in extend
    new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
MemoryError
Command exited with non-zero status 1`

**Comment by zhaoyongle1531** [comment]
I have the same problem.ITERS=70000. But when item = 52520, errors appeared.
MemoryError
Command exited with non-zero status 1
32490.94user 2435.27system 2:27:12elapsed 395%CPU (0avgtext+0avgdata 4780380maxresident)k
4720104inputs+12693736outputs (1277major+31325630minor)pagefaults 0swaps
