### ISSUE TITLE
Crash while training on COCO 2014

### ISSUE THREAD

**Issue by ankur6ue** [ruotianluo/pytorch-faster-rcnn#48]
While training on COCO 2014 dataset, I'm running into the following crash:

![image](https://user-images.githubusercontent.com/6232547/33665660-4d07580a-da5d-11e7-9f10-96f7525e457c.png)

both bg_inds.numel() and fg_inds.numel() is 0, which leads to a crash in keep_inds = torch.cat([fg_inds, bg_inds], 0)

I'm using pytorch on windows, running the program using the following parameters:

--imdb coco_2014_train+coco_2014_val --imdbval coco_2014_val --weight C:\path-to\pytorch-faster-rcnn\data\imagenet_weights\res50.pth

As you do in your training shell scripts, I added an extra element to the anchors:

cfg.ANCHOR_SCALES = [4, 8, 16, 32]

any ideas? Sounds like there should be an exit from the function if no background or foreground regions are found?

**Comment by ankur6ue** [comment]
This happens in the middle of the training. The full python stack trace is here:

>>> rpn_loss_box: 0.032325
 >>> loss_cls: 0.576470
 >>> loss_box: 0.398267
 >>> lr: 0.001000
speed: 0.460s / iter
iter: 21910 / 70000, total loss: 2.657034
 >>> rpn_loss_cls: 0.975540
 >>> rpn_loss_box: 0.671567
 >>> loss_cls: 0.625927
 >>> loss_box: 0.384000
 >>> lr: 0.001000
speed: 0.460s / iter

PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "C:\Anaconda3\lib\bdb.py", line 251, in set_trace
    sys.settrace(self.trace_dispatch)

> c:\telesens\dev\ml\pytorch\pytorch-faster-rcnn\lib\layer_utils\proposal_target_layer.py(142)_sample_rois()
-> keep_inds = torch.cat([fg_inds, bg_inds], 0)
(Pdb) dbcont
*** NameError: name 'dbcont' is not defined
(Pdb) continue

PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "C:\Anaconda3\lib\bdb.py", line 258, in set_continue
    sys.settrace(None)

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.4\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.4\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools/trainval_net.py", line 139, in <module>
    max_iters=args.max_iters)
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools\..\lib\model\train_val.py", line 348, in train_net
    sw.train_model(max_iters)
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools\..\lib\model\train_val.py", line 265, in train_model
    self.net.train_step(blobs, self.optimizer)
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools\..\lib\nets\network.py", line 452, in train_step
    self.forward(blobs['data'], blobs['im_info'], blobs['gt_boxes'])
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools\..\lib\nets\network.py", line 394, in forward
    rois, cls_prob, bbox_pred = self._predict()
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools\..\lib\nets\network.py", line 366, in _predict
    rois = self._region_proposal(net_conv)
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools\..\lib\nets\network.py", line 259, in _region_proposal
    rois, _ = self._proposal_target_layer(rois, roi_scores)
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools\..\lib\nets\network.py", line 157, in _proposal_target_layer
    rois, roi_scores, self._gt_boxes, self._num_classes)
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools\..\lib\layer_utils\proposal_target_layer.py", line 49, in proposal_target_layer
    rois_per_image, _num_classes)
  File "C:/Telesens/dev/ML/PyTorch/pytorch-faster-rcnn/tools\..\lib\layer_utils\proposal_target_layer.py", line 142, in _sample_rois
    keep_inds = torch.cat([fg_inds, bg_inds], 0)
  File "C:\Anaconda3\lib\site-packages\torch\autograd\variable.py", line 88, in __setitem__
    return SetItem.apply(self, key, value)
  File "C:\Anaconda3\lib\site-packages\torch\autograd\_functions\tensor.py", line 117, in forward
    i._set_index(ctx.index, value)
RuntimeError: invalid argument 2: out of range at c:\tmp\pytorch\aten\src\thc\generic/THCTensor.c:23

Process finished with exit code 1

**Comment by YingweiZhou** [comment]
I just met the same issue as your case. When I ran the codes in my local mahcine everything is fine (after some modification to make the codes working without adding extra configs...) but this issue (Pdb) happens when I run my codes in remote server. I'm using PyTorch in Linux.

**Comment by YingweiZhou** [comment]
@ankur6ue Hi, just wondering did you solve this issue in your case? I've tried to change some cfgs but still not working.

**Comment by ankur6ue** [comment]
I haven't yet, as I got looped into other stuff, but basically what is
happening is that neither foreground nor background regions are being found
for that image so it should simply be skipped (no loss computation or back
propagation should be performed). We'll need to add some if's in the code
to handle this case instead of breaking.

**Comment by YingweiZhou** [comment]
@ankur6ue It's weird that after thousands epochs of training, the model seems less likely to produce better bboxes with larger value of overlapping, since the direct reason for this issue is NO value is larger than the threshold which is 0.5 by default. Training the model for thousands of epochs is supposed to make the `max_overlaps` better not worse. The loss value through my trianing process is larger than the loss of my local machine as well.  

`fg_inds=(max_overlaps >= cfg.TRAIN.FG_THRESH).nonzero().view(-1)`
`bg_inds=((max_overlaps < cfg.TRAIN.BG_THRESH_HI) + (max_overlaps >= cfg.TRAIN.BG_THRESH_LO) == 2).nonzero().view(-1)`

It's an even more weird and confusing thing that the codes runs fine in my local machine but when I move the codes to a remote workstation this issue keeps happening no matter how many times I tried to re-setup the codes/ dataset/ environments (using same version of PyTorch and TorchVision). I'll do a deep diging on the codes and try to make it working....

**Comment by akumar14** [comment]
Did anyone solve this issue ?

**Comment by mengce97** [comment]
hello, did u fix it？ 
I meet the same error and i tries it all day with no help.
If you know why it happens, please tell me, i will be very appretriate!

**Comment by xinyanyang** [comment]
Did anyone fix it?
