### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by yhz5256** [ruotianluo/pytorch-faster-rcnn#59]
Traceback (most recent call last):
  File "/home/yang/pytorch-faster-rcnn/tools/convert_from_tensorflow_vgg.py", line 2, in <module>
    import torch
  File "/usr/local/lib/python2.7/dist-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: dlopen: cannot load any more object with static TLS

how to solve this problem?

**Comment by ruotianluo** [comment]
Try changing the order of import.

**Comment by yhz5256** [comment]
@ruotianluo  I have tried to do this,But show"Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"
