### ISSUE TITLE
something wrong when appending  horizontally-flipped training example...

### ISSUE THREAD

**Issue by Destinyzs** [ruotianluo/pytorch-faster-rcnn#75]
I am training my own dataset,but when appending  horizontally-flipped training example,some errors occur like following:
```
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/trainval_net.py", line 75, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 72, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/data2/lczheng/pytorch-faster-rcnn-vg/tools/../lib/model/train_val.py", line 304, in get_training_roidb
    imdb.append_flipped_images()
  File "/data2/lczheng/pytorch-faster-rcnn-vg/tools/../lib/datasets/imdb.py", line 119, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError
```
Can you help me?

**Comment by ruotianluo** [comment]
I'm not familiar the imdb part. Sorry.

**Comment by zeruniverse** [comment]
I got the same error once.

You should make sure your xs and ys for boxes are all $>=2$ and $<= size - 1$. In addition, you may want to comment out the `assert` sentence which causes the error. But my problem was solved only by adjusting the coordinates.

**Comment by Destinyzs** [comment]
Yes,i have found this problem.
In my dataset's bounding box, some coordinates will be <2 after adjusted.I have modified the code.Thanks a lot !

**Comment by Destinyzs** [comment]
```
def f_less2(x):  ## make sure the point x >2
  if x<2:
    x = 2
  return x
def f_less_width(x):  ## make sure the point does not > size
  return min(widths[i], x)

boxes[:, 0] = np.array([map(f_less2, widths[i] - np.array(map(f_less_width, oldx2)))]) - 1
boxes[:, 2] = np.array([map(f_less2, widths[i] - np.array(map(f_less_width, oldx1)))]) - 1
```
This is my solution to my dataset, hope that it will be helpful!
