### ISSUE TITLE
train with res101

### ISSUE THREAD

**Issue by Destinyzs** [ruotianluo/pytorch-faster-rcnn#76]
I download the` res101-caffe.pth` from `https://drive.google.com/file/d/0B7fNdx_jAqhtaXZ4aWppWV96czg/view`.
And rename`res101-caffe` to `res101`.
But some errors:
```
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/data2/lczheng/pytorch-faster-rcnn-vg/tools/../lib/model/train_val.py", line 350, in train_net
    sw.train_model(max_iters)
  File "/data2/lczheng/pytorch-faster-rcnn-vg/tools/../lib/model/train_val.py", line 217, in train_model
    lr, train_op = self.construct_graph()
  File "/data2/lczheng/pytorch-faster-rcnn-vg/tools/../lib/model/train_val.py", line 126, in construct_graph
    for key, value in dict(self.net.named_parameters()).items():
  File "/root/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 235, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'resnetv1' object has no attribute 'named_parameters'
Command exited with non-zero status 1

```
How can i do to solve it?

**Comment by ruotianluo** [comment]
What version is pytorch are you using.

**Comment by Destinyzs** [comment]
My version is 0.3.0

**Comment by ruotianluo** [comment]
Very weird.  Can you print the type of self.net?

**Comment by Destinyzs** [comment]
Oh,i am very sorry! I modified the version of pytorch before.
But i change a machine today,the version is 0.1.9. Forget to update it!
Sorry!
