### ISSUE TITLE
No module named_crop_and_resize

### ISSUE THREAD

**Issue by Licf23** [ruotianluo/pytorch-faster-rcnn#78]
Hi~ 
I very much appreciate you made this repository publicly available to use. Before getting my hands dirtier, I tried to run ./experiments/scripts/train_faster-rcnn.sh; however, got the following error....
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 20, in <module>
    from nets.vgg16 import vgg16
  File "/home/handsome/pycode/pytorch-faster-rcnn/tools/../lib/nets/vgg16.py", line 10, in <module>
    from nets.network import Network
  File "/home/handsome/pycode/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 28, in <module>
    from layer_utils.roi_align.crop_and_resize import CropAndResizeFunction
  File "/home/handsome/pycode/pytorch-faster-rcnn/tools/../lib/layer_utils/roi_align/crop_and_resize.py", line 7, in <module>
    from ._ext import crop_and_resize as _backend
  File "/home/handsome/pycode/pytorch-faster-rcnn/tools/../lib/layer_utils/roi_align/_ext/crop_and_resize/__init__.py", line 3, in <module>
    from ._crop_and_resize import lib as _lib, ffi as _ffi
ImportError: No module named _crop_and_resize
Command exited with non-zero status 1
0.82user 0.58system 0:00.95elapsed 147%CPU (0avgtext+0avgdata 201868maxresident)k
0inputs+32outputs (0major+30395minor)pagefaults 0swaps
Thank you very much !
Could you send me pre_trained model from google drive ? I could not interview that links

**Comment by ruotianluo** [comment]
I guess the reason is you didn't compile the module correctly? Did you do step two without error?

The google drive link should work.

**Comment by Licf23** [comment]
thank you very very very much
