### ISSUE TITLE
The rpn_loss_box becomes nan  after 200 iters

### ISSUE THREAD

**Issue by AdamGoodwin617** [ruotianluo/pytorch-faster-rcnn#82]
Hi,
I am training on a custom dataset set up similar to pascal. It seems like training is going well, then at 200 iters, the rpn_loss_box and the total loss become `nan`
`
iter: 160 / 70000, total loss: 0.622355
 >>> rpn_loss_cls: 0.222271`
 >>> rpn_loss_box: 0.055740
 >>> loss_cls: 0.243889
 >>> loss_box: 0.100454
 >>> lr: 0.001000
speed: 0.167s / iter
iter: 180 / 70000, total loss: 0.248979
 >>> rpn_loss_cls: 0.151246
 >>> rpn_loss_box: 0.003199
 >>> loss_cls: 0.065148
 >>> loss_box: 0.029386
 >>> lr: 0.001000
speed: 0.163s / iter
iter: 200 / 70000, total loss: nan
 >>> rpn_loss_cls: 0.664166
 >>> rpn_loss_box: nan
 >>> loss_cls: 0.000050
 >>> loss_box: 0.000000
 >>> lr: 0.001000
speed: 0.160s / iter
iter: 220 / 70000, total loss: nan
 >>> rpn_loss_cls: 0.642187
 >>> rpn_loss_box: nan
 >>> loss_cls: 0.000054
 >>> loss_box: 0.000000
 >>> lr: 0.001000
speed: 0.157s / iter
iter: 240 / 70000, total loss: nan
 >>> rpn_loss_cls: 0.632327
 >>> rpn_loss_box: nan
 >>> loss_cls: 0.000054
 >>> loss_box: 0.000000
 >>> lr: 0.001000
speed: 0.154s / iter
`
Also, it terminates at about 1320 or 1340 iters. I think this is more a symptom than a problem itself, given the errors thrown:

`
iter: 1320 / 70000, total loss: nan
 >>> rpn_loss_cls: 0.233524
 >>> rpn_loss_box: nan
 >>> loss_cls: 0.000418
 >>> loss_box: 0.000000
 >>> lr: 0.001000
speed: 0.135s / iter
/home/vectorweb3/.local/lib/python2.7/site-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
/home/vectorweb3/.local/lib/python2.7/site-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/home/vectorweb3/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 348, in train_net
    sw.train_model(max_iters)
  File "/home/vectorweb3/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 255, in train_model
    self.net.train_step_with_summary(blobs, self.optimizer)
  File "/home/vectorweb3/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 468, in train_step_with_summary
    summary = self._run_summary_op()
  File "/home/vectorweb3/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 333, in _run_summary_op
    summaries.append(self._add_score_summary(key, var))
  File "/home/vectorweb3/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 72, in _add_score_summary
    return tb.summary.histogram('SCORE/' + key + '/scores', tensor.data.cpu().numpy(), bins='auto')
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/summary.py", line 112, in histogram
    hist = make_histogram(values.astype(float), bins)
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/summary.py", line 119, in make_histogram
    counts, limits = np.histogram(values, bins=bins)
  File "/home/vectorweb3/.local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 670, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.
Command exited with non-zero status 1
174.53user 48.27system 3:37.50elapsed 102%CPU (0avgtext+0avgdata 4790488maxresident)k
304inputs+1984outputs (0major+1550948minor)pagefaults 0swaps`

Any help is appreciated!

**Comment by zeruniverse** [comment]
You can't have $xmin=0$, $ymin=0$, $xmax=width$ or $ymax=height$ in your dataset ground truth boxes. Otherwise, you will have nan error.

**Comment by AdamGoodwin617** [comment]
I gave that a go and checked my annotations. Now, none are within a few pixels of the edge now (I pulled them all in a pixel if they were), but the issues persist still starting at iter 200. Any other suggestions?
A few odd things about my situation:

- I had a similar custom dataset that I have already run on successfully. The primary difference between the datasets is that the successful one had larger images and had much fewer images.
- My new dataset contains smaller images (450x450), and there are many images that have no objects in them. Could this be problematic? 
I checked the VOC dataset and there aren't any annotations with no objects in them, so that is the primary difference I am thinking right now... your thoughts?

**Comment by AdamGoodwin617** [comment]
Nevermind! I had forgotten to clear the /data/cache. Looks like its training just fine! Thanks a lot!

**Comment by CoderHHX** [comment]
I am also meet this problem. I have deleted the Cache files and I also make the gt boxes size as @zeruniverse  says but I still get a NAN line in rpn_loss_box
iter: 120 / 70000, total loss: 1.312589
 >>> rpn_loss_cls: 0.471951
 >>> rpn_loss_box: 0.668822
 >>> loss_cls: 0.135918
 >>> loss_box: 0.035899
 >>> lr: 0.001000
speed: 0.626s / iter
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 379, in train_net
    sw.train_model(max_iters)
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 267, in train_model
    self.net.train_step(blobs, self.optimizer)
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 447, in train_step
    self.forward(blobs['data'], blobs['im_info'], blobs['gt_boxes'])
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 396, in forward
    self._add_losses() # compute losses
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 198, in _add_losses
    assert (rpn_bbox_pred==rpn_bbox_pred).all()
AssertionError
