### ISSUE TITLE
Custom Dataset Evaluation either 0.0 or nan

### ISSUE THREAD

**Issue by agoodwin617** [ruotianluo/pytorch-faster-rcnn#84]
Hi,
I have a custom dataset set up like VOC.  I have trained successfully, but when I evaluate, however, I get either nan or 0.00 depending o whether or not I use the 07 metric or not. `use_metric_07=True` gives me 0.00, and `use_metric_07=False` gives me nan. 
Any suggestions on possible solutions? Outputs below:
For `True`:
```
Saving cached annotations to /home/vectorweb3/pytorch-faster-rcnn/data/smlchunksdevkitsml/smlchunkssml/ImageSets/Main/test.txt_annots.pkl
/home/vectorweb3/pytorch-faster-rcnn/tools/../lib/datasets/smlchunks_eval.py:205: RuntimeWarning: invalid value encountered in true_divide
  rec = tp / float(npos)
/home/vectorweb3/pytorch-faster-rcnn/tools/../lib/datasets/smlchunks_eval.py:42: RuntimeWarning: invalid value encountered in greater_equal
  if np.sum(rec >= t) == 0:
AP for bre = 0.0000
AP for lymphocyte = 0.0000
Mean AP = 0.0000
~~~~~~~~
Results:
0.000
0.000
0.000
~~~~~~~~
```
For `False`:
```
Evaluating detections
Writing bre smlchunks results file
Writing lymphocyte smlchunks results file
smlchunks07 metric? No
/home/vectorweb3/pytorch-faster-rcnn/tools/../lib/datasets/smlchunks_eval.py:205: RuntimeWarning: invalid value encountered in true_divide
  rec = tp / float(npos)
AP for bre = nan
AP for lymphocyte = nan
Mean AP = nan
~~~~~~~~
Results:
nan
nan
nan
~~~~~~~~
```

**Comment by CoderHHX** [comment]
I meet a problem that when I train the model in 140 iters , the rpn_loss_box will be NAN so as to total_loss. I use VisDrone Dataset and transform it to the VOC format.
iter: 100 / 70000, total loss: 1.238060
 >>> rpn_loss_cls: 0.503647
 >>> rpn_loss_box: 0.560238
 >>> loss_cls: 0.128045
 >>> loss_box: 0.046130
 >>> lr: 0.001000
speed: 0.645s / iter
iter: 120 / 70000, total loss: 1.312589
 >>> rpn_loss_cls: 0.471951
 >>> rpn_loss_box: 0.668822
 >>> loss_cls: 0.135918
 >>> loss_box: 0.035899
 >>> lr: 0.001000
speed: 0.626s / iter
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 379, in train_net
    sw.train_model(max_iters)
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 267, in train_model
    self.net.train_step(blobs, self.optimizer)
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 447, in train_step
    self.forward(blobs['data'], blobs['im_info'], blobs['gt_boxes'])
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 396, in forward
    self._add_losses() # compute losses
  File "/data/huaxhuan/FasterRCNN/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 198, in _add_losses
    assert (rpn_bbox_pred==rpn_bbox_pred).all()
AssertionError

**Comment by lcf000000** [comment]
> I believe that the problem is that I did not include any marking for 'difficult' in my annotations. I think I need to change the customdataset_eval.py function to no longer rely on the 'difficult' part of the annotation. Can someone verify if this is correct?

Did you fix this problem?

**Comment by mrxiaohe** [comment]
@lcf000000 @TVXQ20031226 @AdamGoodwin617 : I ran into the same problem. What fixed it for me was changing all the class names in the xml files to lowercases, but YMMV.
