### ISSUE TITLE
Error: 'vgg16' object has no attribute 'to'

### ISSUE THREAD

**Issue by lingxiao7** [ruotianluo/pytorch-faster-rcnn#88]
When i want to train a custom data. There are 94 classes in the custom data, and i modify the code.

```
// pascal_voc.py
self._classes = ('__background__',  # always index 0      totol: 1 + 94              
                    '0','1','2','59','4','5','6','7','8','15','10','11','12','13','82',
                    '16','17','18','19','20','21','22','23','24','25','26','27','28',
                    '29','30','31','32','33','34','35','36','87','38','39','40','41',
                    '42','43','44','45','47','48','49','50','51','52','53','54','55',
                    '56','57','58','3','60','70','62','63','64','65','66','67','68',
                    '69','61','46','72','73','81','75','76','77','78','79','80','74',
                    '14','83','84','85','86','37','88','71','89','90','91','92','9','93')
```

I meet some problem. More details following. What could i do next?

```
Loaded.
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/home/lingxiao/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 348, in train_net
    sw.train_model(max_iters)
  File "/home/lingxiao/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 236, in train_model
    self.net.to(self.net._device)
  File "/home/lingxiao/anaconda3/envs/py_rcnn/lib/python2.7/site-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'vgg16' object has no attribute 'to'
Command exited with non-zero status 1
```

**Comment by qiaoD** [comment]
I have same problem,I check the Doc of  torch and you should upgrade your torch to 0.4:
`pip install -U torch`
