### ISSUE TITLE
AttributeError: 'resnetv1' object has no attribute 'to'

### ISSUE THREAD

**Issue by qiaoD** [ruotianluo/pytorch-faster-rcnn#90]
When I run it ,I meet this error,what should I do?

```python
Traceback (most recent call last):
  File "./tools/test_net.py", line 109, in <module>
    net.to(net._device)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'resnetv1' object has no attribute 'to'
```

**Comment by ruotianluo** [comment]
update to pytorch 0.4
