### ISSUE TITLE
ImportError: ../_roi_pooling.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by hesedjds** [ruotianluo/pytorch-faster-rcnn#92]
Hi, Thank you for your great work.
I have some error with roi_pooling layer (also nms and roi_align).

`Traceback (most recent call last):
  File "./tools/test_net.py", line 18, in <module>
    from nets.vgg16 import vgg16
  File "/home/sarairon/PycharmProjects/pytorch-faster-rcnn/tools/../lib/nets/vgg16.py", line 10, in <module>
    from nets.network import Network
  File "/home/sarairon/PycharmProjects/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 27, in <module>
    from layer_utils.roi_pooling.roi_pool import RoIPoolFunction
  File "/home/sarairon/PycharmProjects/pytorch-faster-rcnn/tools/../lib/layer_utils/roi_pooling/roi_pool.py", line 3, in <module>
    from ._ext import roi_pooling
  File "/home/sarairon/PycharmProjects/pytorch-faster-rcnn/tools/../lib/layer_utils/roi_pooling/_ext/roi_pooling/__init__.py", line 3, in <module>
    from ._roi_pooling import lib as _lib, ffi as _ffi
ImportError: /home/sarairon/PycharmProjects/pytorch-faster-rcnn/tools/../lib/layer_utils/roi_pooling/_ext/roi_pooling/_roi_pooling.so: undefined symbol: __cudaPopCallConfiguration
`

Above error is appeared, so I cannot run the code. 
Have you ever seen this error before? I used cuda 9.0 and pytorch 0.4, cudnn 7.1 for running.

**Comment by zimenglan-sysu-512** [comment]
hi @hesedjds 
have u solved this problem?
