### ISSUE TITLE
error when train by myself with "./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc res101"

### ISSUE THREAD

**Issue by SkylerZheng** [ruotianluo/pytorch-faster-rcnn#95]
4952 validation roidb entries
Filtered 0 roidb entries: 10022 -> 10022
Filtered 0 roidb entries: 4952 -> 4952
Solving...
Loading initial model weights from data/imagenet_weights/res101.pth
Loaded.
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 138, in <module>
    max_iters=args.max_iters)
  File "/home/jzheng/PycharmProjects/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 348, in train_net
    sw.train_model(max_iters)
  File "/home/jzheng/PycharmProjects/pytorch-faster-rcnn/tools/../lib/model/train_val.py", line 255, in train_model
    self.net.train_step_with_summary(blobs, self.optimizer)
  File "/home/jzheng/PycharmProjects/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 470, in train_step_with_summary
    summary = self._run_summary_op()
  File "/home/jzheng/PycharmProjects/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 326, in _run_summary_op
    summaries.append(self._add_gt_image_summary())
  File "/home/jzheng/PycharmProjects/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 65, in _add_gt_image_summary
    return tb.summary.image('GROUND_TRUTH', image[0].astype('float32')/255.0)
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/summary.py", line 172, in image
    image = make_image(tensor)
  File "/usr/local/lib/python2.7/dist-packages/tensorboardX/summary.py", line 180, in make_image
    image = Image.fromarray(tensor)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2431, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
Command exited with non-zero status 1

**Comment by LightningChan** [comment]
I have met this problem also. Could you share how to solve it?

**Comment by SkylerZheng** [comment]
I think there's something wrong with the tensorboardX, so I commented those lines because I don't need to use tensorboard to show me those summaries. And once you have commented those relevant lines, it will be working fine.

**Comment by LightningChan** [comment]
@SkylerZheng Thanks! It works!

**Comment by Kinpzz** [comment]
I have the same problem.

**Comment by zwbdmm** [comment]
@LightningChan Could you specify where did you make the change, struggling with it now.

**Comment by Kinpzz** [comment]
@zwbdmm  Sorry, I mean I have the same issue when I am using the latest tensorboardX. But tensorflowboard==1.2 solves the problem.

**Comment by sgflower66** [comment]
@Kinpzz Thanks for your solution,I solve it. Then I met a new problem:(
Do you know how to  solve it?

  File "/home/pytorch-faster-rcnn/tools/../lib/nets/network.py", line 87, in _proposal_layer
    self._feat_stride, self._anchors, self._num_anchors)
  File "/home/pytorch-faster-rcnn/tools/../lib/layer_utils/proposal_layer.py", line 35, in proposal_layer
    scores, order = scores.view(-1).sort(descending=True)
RuntimeError: merge_sort: failed to synchronize: an illegal memory access was encountered

**Comment by foralliance** [comment]
@Kinpzz  HI
My tensorboardX is 1.4 version . How do I download version 1.2??
many many thanks!!!

**Comment by lcf000000** [comment]
> @zwbdmm Sorry, I mean I have the same issue when I am using the latest tensorboardX. But tensorflowboard==1.2 solves the problem.

Thanks, it works for me ! 
Just change tensorboardX to 1.2
